<?php

use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('settings')->delete();

        \DB::table('settings')->insert([
            [
                'key'          => 'title',
                'display_name' => 'Site Title',
                'value'        => 'Site Title',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 1,
            ],
            [
                'key'          => 'url',
                'display_name' => 'Site Url',
                'value'        => 'http://www.example.com',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 1,
            ],
            [
                'key'          => 'ar_title',
                'display_name' => 'Site Title In Arabic',
                'value'        => 'Site Title',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 2,
            ],
            [
                'key'          => 'en_title',
                'display_name' => 'Site Title In English',
                'value'        => 'Site Title',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 3,
            ],
            [
                'key'          => 'ar_meta_description',
                'display_name' => 'Site Description In Arabic',
                'value'        => 'Site Description',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text_area',
                'order'        => 4,
            ],
            [
                'key'          => 'en_meta_description',
                'display_name' => 'Site Description In English',
                'value'        => 'Site Description',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text_area',
                'order'        => 5,
            ],
            [
                'key'          => 'ar_meta_tags',
                'display_name' => 'Meta Tags In Arabic',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text_area',
                'order'        => 6,
            ],
            [
                'key'          => 'en_meta_tags',
                'display_name' => 'Meta Tags In English',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text_area',
                'order'        => 7,
            ],
            [

                'key'          => 'logo',
                'display_name' => 'Site Logo',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'image',
                'order'        => 8,
            ],
            [
                'key'          => 'favicon',
                'display_name' => 'Website Icon',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'image',
                'order'        => 8,
            ],
            [
                'key'          => 'admin_bg_image',
                'display_name' => 'Admin Background Image',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'image',
                'order'        => 9,
            ],
            [
                'key'          => 'admin_title',
                'display_name' => 'Admin Title',
                'value'        => 'DevelopNet',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 10,
            ],
            [
                'key'          => 'admin_description',
                'display_name' => 'Admin Description',
                'value'        => 'Welcome Back to Admin Panel',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 11,
            ],
            [
                'key'          => 'google_analytics_client_id',
                'display_name' => 'Google Analytics Client ID',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 12,
            ],
            [
                'key'          => 'backend_uri',
                'display_name' => 'Backend URI',
                'value'        => 'admin',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 13,
            ],

            [
                'key'          => 'slogan',
                'display_name' => 'Website Slogan',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 15,
            ],
            [
                'key'          => 'country_institutes_count',
                'display_name' => 'Number Of Institutes In Country Page',
                'value'        => '5',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 16,
            ],
            [
                'key'          => 'country_places_count',
                'display_name' => 'Number Of Places in Country Page',
                'value'        => '5',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 17,
            ],
            [
                'key'          => 'country_packages_count',
                'display_name' => 'Number Of Packages in Country Page',
                'value'        => '5',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 17,
            ],
            [
                'key'          => 'home_country_count',
                'display_name' => 'Number Of Countries in Home Page',
                'value'        => '3',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 18,
            ],
            [
                'key'          => 'home_packages_count',
                'display_name' => 'Number Of Packages in Home Page',
                'value'        => '3',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 19,
            ],
            [
                'key'          => 'help_email',
                'display_name' => 'Site email fore help',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 20,
            ],
            [
                'key'          => 'help_phone',
                'display_name' => 'Phone Number fore help',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 21,
            ], [
                'key'          => 'home_packages_section_background',
                'display_name' => 'Background for Packages Section ',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'image',
                'order'        => 23,
            ], [
                'key'          => 'home_packages_section_photo',
                'display_name' => 'Photo for Packages Section ',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'image',
                'order'        => 24,
            ],

            [
                'key'          => 'blog',
                'display_name' => 'blog URL',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 25,
            ],
            [
                'key'          => 'googleplus',
                'display_name' => 'google plus URL',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 26,
            ],
            [
                'key'          => 'facebook',
                'display_name' => 'facebook URL',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 27,
            ],
            [
                'key'          => 'instagram',
                'display_name' => 'instagram URL',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 27,
            ],
            [
                'key'          => 'twitter',
                'display_name' => 'twitter URL',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 27,
            ],
            [
                'key'          => 'snapchat',
                'display_name' => 'snapchat URL',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 27,
            ],
            [
                'key'          => 'linkedin',
                'display_name' => 'linkedin URL',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 28,
            ],
            [
                'key'          => 'vimeo',
                'display_name' => 'vimeo URL',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 29,
            ],
            ['key'          => 'dribble',
             'display_name' => 'dribble URL',
             'value'        => '',
             'details'      => '',
             'category'     => 'general',
             'type'         => 'text',
             'order'        => 30,
            ],
            [
                'key'          => 'flickr',
                'display_name' => 'flickr URL',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 31,
            ],
            [
                'key'          => 'youtube',
                'display_name' => 'Youtube URL',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 30,
            ],
            [
                'key'          => 'whatsapp_number',
                'display_name' => 'whatsapp Number',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 31,
            ],

            [
                'key'          => 'show_help_box',
                'display_name' => 'Show Help Box',
                'value'        => '1',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'checkbox',
                'order'        => 31,
            ],

            [
                'key'          => 'ar_help_box_title',
                'display_name' => 'Help box title in Arabic',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 32,
            ],
            [
                'key'          => 'en_help_box_title',
                'display_name' => 'Help box title in English',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 33,
            ],
            [
                'key'          => 'ar_help_box_details',
                'display_name' => 'Help box details in Arabic',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'rich_text_box',
                'order'        => 34,
            ],
            [
                'key'          => 'en_help_box_details',
                'display_name' => 'Help box details in English',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'rich_text_box',
                'order'        => 35,
            ],
            [
                'key'          => 'en_currency',
                'display_name' => 'Currency Name in English',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 36,
            ],
            [
                'key'          => 'ar_currency',
                'display_name' => 'Currency name In Arabic',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 37,
            ],
            [
                'key'          => 'currency_on_right',
                'display_name' => 'Show currency symbol on right of price',
                'value'        => '1',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'checkbox',
                'order'        => 38,
            ],
            [
                'key'          => 'header_video',
                'display_name' => 'Header Video - فيديو الرئيسية',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'video',
                'order'        => 39,
            ],
             [
                'key'          => 'header_image',
                'display_name' => 'Header Image - صورة الرئيسية',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'video',
                'order'        => 39,
            ],
            [
                'key'          => 'steps_video_youtube',
                'display_name' => 'How it work (youtube)',
                'value'        => 'https://www.youtube.com/embed/oufbHSMY0U0?rel=0',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 40,
            ],
            [
                'key'          => 'steps_video_thumbnail',
                'display_name' => 'How it work fixed image',
                'value'        => '',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'image',
                'order'        => 41,
            ],

             [
                'key'          => 'home_slider_title_ar',
                'display_name' => 'العنوان على السلايدر بالرئيسية - AR',
                'value'        => 'أفضل عروض دورات اللغة الإنجليزية بالخارج',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 42,
            ],
            [
                'key'          => 'home_slider_title_en',
                'display_name' => 'Title on Home Slider',
                'value'        => 'Best English Institutes',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 43,
            ],
              [
                'key'          => 'home_slider_description_ar',
                'display_name' => 'الوصف على السلايدر بالرئيسية - AR',
                'value'        => 'ابحث بين اكثر من 1000 معهد لغة موصي به حول العالم .. وعيش تجربة التعلم بالخارج',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 44,
            ],
            [
                'key'          => 'home_slider_description_en',
                'display_name' => 'Description on Home Slider',
                'value'        => 'Search between Best English Institutes',
                'details'      => '',
                'category'     => 'general',
                'type'         => 'text',
                'order'        => 45,
            ],
            
            
        ]);


    }
}
